# Roles - for write operation
# kuriakosej
 # UserAdmin - can create users and assign roles
 # Trader - can request Bonds assignment
# astala
 # CompanyAdmin - can create Terms
# simpsonh
 # Trader - can request Bonds assignment

### Create Admin User using Super User G_D
POST http://localhost:9096/api/users
Authorization: Basic G_D dummypasswd
Content-Type: application/json

{
  "userName": "kuriakosej",
  "password": "@#$@#%",
  "name": "Jubin"
}

### Create other users using UserAdmin
POST http://localhost:9096/api/users
Authorization: Basic kuriakosej dummypasswd
Content-Type: application/json

{
  "userName": "simpsonh",
  "password": "@#$@#%",
  "name": "Homer"
}

### GET user G_D
GET http://localhost:9096/api/user/G_D

### GET user kuriakosej
GET http://localhost:9096/api/user/kuriakosej

### GET user astala
GET http://localhost:9096/api/user/astala

### GET user simpsonh
GET http://localhost:9096/api/user/simpsonh


### Assign Role with UserAdmin Role
POST http://localhost:9096/api/user/roles
Authorization: Basic kuriakosej dummypasswd
Content-Type: application/json

{
  "userId": "simpsonh",
  "role": "Trader"
}

### GET User Roles
GET http://localhost:9096/api/user/roles/simpsonh

### Create Bond Terms by CompanyAdmin
POST http://localhost:9096/api/terms/issue
Authorization: Basic astala dummypasswd
Content-Type: application/json

{
  "bondName": "test04",
  "bondType": "GB",
  "creditRating": "C",
  "currency": "USD",
  "interestRate": 12.4,
  "maturityDate": "20540824",
  "parValue": 1000,
  "unitsAvailable": 2430,
  "paymentFrequencyInMonths": 12
}

### GET Term 01
GET http://localhost:9096/api/terms/test01

### GET Term 02
GET http://localhost:9096/api/terms/test02

### GET Term 03
GET http://localhost:9096/api/terms/test03

### GET Term 04
GET http://localhost:9096/api/terms/test04


### Assign Trader (Authorization header) a Bond
POST http://localhost:9096/api/bonds/assign
Authorization: Basic kuriakosej dummypasswd
Content-Type: application/json

{
  "bondName": "test03",
  "unitsAssigned": 50
}



### Get Bonds Assigned to simpsonh
GET http://localhost:9096/api/bonds/assigned/simpsonh

### Get Bonds Assigned to kuriakosej
GET http://localhost:9096/api/bonds/assigned/kuriakosej

### Get Bond Details for test01-1
GET http://localhost:9096/api/bonds/details/test01-1

### Get Bond Details for test02-2
GET http://localhost:9096/api/bonds/details/test02-2

### Get All Bond Details
GET http://localhost:9096/api/bonds/details/all


### Get All Keys registered
GET http://localhost:9096/api/keys
Content-Type: application/json

{
  "pattern": "*"
}

### Get Keys by pattern
GET http://localhost:9096/api/keys
Content-Type: application/json

{
  "pattern": "corda:bt:bond:details#*"
}

### Get Keys by pattern
GET http://localhost:9096/api/keys
Content-Type: application/json

{
"pattern": "corda:users#*"
}