###
POST http://localhost:9096/api/users
Content-Type: application/json

{
  "userName": "simpsonh",
  "password": "@#$@#%",
  "name": "Homer",
  "role": "QA"
}

###
GET http://localhost:9096/api/user/kuriakosej

<> 2022-08-25T100350.200.json

###
GET http://localhost:9096/api/user/astala

###
GET http://localhost:9096/api/user/simpsonh

<> 2022-08-25T100354.200.json

###
POST http://localhost:9096/api/terms/issue
Content-Type: application/json

{
  "bondName": "test01",
  "bondType": "GB",
  "creditRating": "AAA",
  "currency": "USD",
  "interestRate": 2.4,
  "maturityDate": "20230824",
  "parValue": 500,
  "unitsAvailable": 1000,
  "paymentFrequencyInMonths": 12
}

###
POST http://localhost:9096/api/terms/issue
Content-Type: application/json

{
  "bondName": "test02",
  "bondType": "GB",
  "creditRating": "B-",
  "currency": "USD",
  "interestRate": 5.4,
  "maturityDate": "20240824",
  "parValue": 600,
  "unitsAvailable": 1000,
  "paymentFrequencyInMonths": 12
}

<> 2022-08-25T100145.200.json
###
POST http://localhost:9096/api/terms/issue
Content-Type: application/json

{
  "bondName": "test03",
  "bondType": "GB",
  "creditRating": "AAA",
  "currency": "SGD",
  "interestRate": 2.4,
  "maturityDate": "20230824",
  "parValue": 500,
  "unitsAvailable": 1000,
  "paymentFrequencyInMonths": 12
}

###
GET http://localhost:9096/api/terms/test01

###
GET http://localhost:9096/api/terms/test02

###
GET http://localhost:9096/api/terms/test03

