# Roles - for write operation
# kuriakosej
 # UserAdmin - can create users and assign roles
 # Trader - can assigned Bonds
# astala
 # CompanyAdmin - can create Terms
# simpsonh
 # Trader - can request Bonds assignment

###
POST http://localhost:9096/api/users
Authorization: Basic kuriakosej dummypasswd
Content-Type: application/json

{
  "userName": "testDummy",
  "password": "@#$@#%",
  "name": "dummy",
  "role": "PLA"
}

###
GET http://localhost:9096/api/user/kuriakosej

###
GET http://localhost:9096/api/user/astala

###
GET http://localhost:9096/api/user/simpsonh

###
POST http://localhost:9096/api/user/roles
Authorization: Basic kuriakosej dummypasswd
Content-Type: application/json

{
  "userId": "simpsonh",
  "role": "Trader"
}

###
GET http://localhost:9096/api/user/roles/kuriakosej

###
POST http://localhost:9096/api/terms/issue
Authorization: Basic astala dummypasswd
Content-Type: application/json

{
  "bondName": "test11",
  "bondType": "CB",
  "creditRating": "B-",
  "currency": "USD",
  "interestRate": 5.4,
  "maturityDate": "20300824",
  "parValue": 500,
  "unitsAvailable": 10,
  "paymentFrequencyInMonths": 12
}


###
GET http://localhost:9096/api/terms/test01

###
GET http://localhost:9096/api/terms/test02

###
GET http://localhost:9096/api/terms/test03

